name: saude
description: A new Flutter project.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  built_collection: 5.1.1
  built_value: 8.4.3
  cached_network_image: 3.2.1
  fl_chart: 0.55.0
  flutter_animate: 1.0.0
  flutter_cache_manager: 3.3.0
  flutter_spinkit: 5.1.0
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  intl: ^0.18.1
  json_path: 0.4.1
  json_serializable: 6.6.1
  page_transition: 2.0.4
  plugin_platform_interface: 2.1.3
  provider: 6.0.4
  rxdart: 0.27.4
  shared_preferences: 2.0.15
  timeago: 3.2.2
  url_launcher: 6.1.5
  mask_text_input_formatter: ^2.4.0
  flutter_native_splash: ^2.1.0
  lottie: ^1.0.1
  sidebarx: ^0.2.1
  http: ^0.13.5
  path_provider: ^2.0.11
  carousel_slider: ^4.2.1
  awesome_dialog: ^3.0.2
  awesome_snackbar_content: ^0.1.3
  percent_indicator: ^4.0.1
  google_fonts: ^4.0.4

flutter_icons:
  image_path: "assets/images/logo.png" 
  Android: true
  ios: true


dev_dependencies:
  build_runner: 2.3.3
  built_value_generator: 8.4.3
  flutter_launcher_icons: 0.12.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  